### ISSUE TITLE
Entity: Group

### ISSUE THREAD

**Issue by shahinam** [kashmire/crm-tool#1]
### About
The group is a collection of organisation members.

### Use case
As an organisation admin, I want to:
- create group.
- list various groups in organisation.
- List all details about a group

### Create Group
```
Method: POST
Endpoint: /organizations/:id/groups
Response: 201 + payload / 400 + message
```
#### Payload
```yaml
name: "Engineering"
count: 23
```
---
### GET Group
```
Method: GET
Endpoint: /organizations/:id/group/:id
Response: 200 + payload / 404 + message
```
#### Response
```yaml
id: 9 
name: Engineering
type: group
created_at: 2017-01-14T04:33:35Z
updated_at: 2017-11-18T04:33:35Z
```
---
### GET Groups
```
Method: GET
Endpoint: /organizations/:id/groups
Response: 200 + payload / 404 + message
```
#### Response
```yaml
groups:
  - obj
  - obj
  - obj
```
