### ISSUE TITLE
Entity: User

### ISSUE THREAD

**Issue by skippednote** [kashmire/crm-tool#2]
### About
The User entity holds data corresponding to a person belonging to an Organization.

### Use case
As an Organisation admin, I want to:
- create a User.
- get a specific user's information.
- get a list of all the Users in an Organization.

### Create User
```
Method: POST
Endpoint: /organizations/:id/users
Response: 201 + payload / 400 + message
```
#### Payload
```yaml
username: bassam
site_admin: false
name: "Bassam Ismail"
email: "skippednote@gmail.com"
password: ******
```
---
### GET User
```
Method: POST
Endpoint: /organizations/:id/users/:id
Response: 200 + payload / 404 + message
```
#### Response
```yaml
username: bassam
id: 9 
type: user
site_admin: false
name: "Bassam Ismail"
organization_name: "CRM TOOL"
organization: 2
avatar_url: "s3.bucket_id.amazon.com/skippednote.png"
email: skippednote@gmail.com
created_at: 2017-01-14T04:33:35Z
updated_at: 2017-11-18T04:33:35Z
```
---
### GET Users
```
Method: GET
Endpoint: /organizations/:id/users
Response: 200 + payload / 404 + message
```
#### Response
```yaml
users:
  - user1 obj
  - user2 obj
  - user3 obj
```
