### ISSUE TITLE
Entity: Organisation

### ISSUE THREAD

**Issue by shahinam** [kashmire/crm-tool#3]
### About

The **Organization** entity holds information about an organization.

### Use case

As an owner, I want to:
- create an Organization
- get information about a specific Organization
- get a list of organizations

---

### Create Organization
````
Method: POST
Endpoint: /organizations/
Response: 201 + payload / 400 + message
````
#### Payload
````yaml
name: "My awesome organization"
admin: [user1, user2, ... ]
````
---

### GET Organization
````
Method: GET
Endpoint: /organizations/:id
Response: 200 + payload / 404 + message
````
#### Response
````yaml
id: 2 
name: "My awesome organization"
type: organization
created_at: 2017-01-14T04:33:35Z
updated_at: 2017-11-18T04:33:35Z
````

### GET Groups
````
Method: GET
Endpoint: /organizations
Response: 200 + payload / 404 + message
````
#### Response
````yaml
organizations:
  - organization obj
  - organization obj
  - organization obj

**Comment by nidaismailshah** [comment]
### About

The **Organization** entity holds information about an organization.

### Use case

As an owner, I want to:
- create an Organization
- get information about a specific Organization
- get a list of organizations

---

### Create Organization
````
Method: POST
Endpoint: /organizations/
Response: 201 + payload / 400 + message
````
#### Payload
````yaml
name: "My awesome organization"
admin: [user1, user2, ... ]
````
---

### GET Organization
````
Method: GET
Endpoint: /organizations/:id
Response: 200 + payload / 404 + message
````
#### Response
````yaml
id: 2 
name: "My awesome organization"
type: organization
created_at: 2017-01-14T04:33:35Z
updated_at: 2017-11-18T04:33:35Z
````

### GET Groups
````
Method: GET
Endpoint: /organizations
Response: 200 + payload / 404 + message
````
#### Response
````yaml
organizations:
  - organization obj
  - organization obj
  - organization obj
